export const femaleMaskedOG = {
  "Background": [
    "Aqua.png",
    "Aristocracy.png",
    "Bamboo Gradient.png",
    "Bamboo Purple.png",
    "Bamboo Red.png",
    "Bamboo Tropic.png",
    "Black Hole.png",
    "Bubbles Blue.png",
    "Bubbles Pink.png",
    "Calendar Lilac.png",
    "Calendar Ruby.png",
    "Calendar Violet.png",
    "Celeste.png",
    "Double Moons Cloud.png",
    "Double Moons Dark Blue.png",
    "Double Moons Fire.png",
    "Double Moons Mint.png",
    "Double Moons Yellow.png",
    "Fire.png",
    "Flowers Blue.png",
    "Flowers Grey.png",
    "Flowers Middle Green.png",
    "Forest.png",
    "Gators dark.png",
    "Gradient Blue.png",
    "Gradient Gold.png",
    "Gradient Green.png",
    "Gradient Pink.png",
    "Gradient Purple.png",
    "Gradient Red.png",
    "J_Toons.png",
    "Lavender.png",
    "Leaf Glow.png",
    "Leaf Violet.png",
    "Lilac.png",
    "Lines.png",
    "Marble Blue.png",
    "Marble Malva.png",
    "Marble Pink.png",
    "Mint.png",
    "Mosaic Lilac.png",
    "Pastel Cloud.png",
    "Pink Vector.png",
    "Pyramid Azure.png",
    "Pyramid Dark Blue.png",
    "Pyramid Dark Green.png",
    "Pyramid Dark Pink.png",
    "Pyramid Sunrise.png",
    "Real Pastel.png",
    "Red Vector.png",
    "Ring Glow Pink.png",
    "Ring Mint.png",
    "Sand.png",
    "Skulls Contrast.png",
    "Skulls Dark.png",
    "Skulls Neon.png",
    "Skulls Orange.png",
    "Solid Green.png",
    "Solid Wine.png",
    "Stone Blue.png",
    "Stone Gold.png",
    "Stone Jade.png",
    "Stone Orange.png",
    "Stone Purple.png",
    "Stone Sand.png",
    "Stone Turqoise.png",
    "Sun All Red.png",
    "Sun Gold.png",
    "Sun Yellow.png",
    "Yellow.png",
    "Bubbles Green.png",
    "Double Moons Dark Orange.png",
    "Skulls Black.png",
    "Skulls Red.png",
    "Sun Orange.png"
  ],
  "Body": [
    "Blue.png",
    "Chestnut.png",
    "Green.png",
    "Honey.png",
    "Porcelain.png",
    "Red.png",
    "Siena.png",
    "Warm Ivory.png"
  ],
  "Dress": [
    "Feathers Blue.png",
    "Feathers Bright Green.png",
    "Feathers Green.png",
    "Feathers Orange.png",
    "Feathers Pink.png",
    "Fringes Black.png",
    "Fringes Blue.png",
    "Fringes Fluor.png",
    "Fringes Green.png",
    "Fringes Orange.png",
    "Fringes Pink.png",
    "Fringes Purple.png",
    "Fringes Red.png",
    "Fringes Yellow.png",
    "Jewel Blue.png",
    "Jewel Brown.png",
    "Jewel Flowers Blue.png",
    "Jewel Flowers Violet.png",
    "Jewel Flowers.png",
    "Jewel Red.png",
    "Jewel Turquoise.png",
    "Pattern Dress.png",
    "Pattern Tattoo Turquoise.png",
    "Pink Stripes Blue.png",
    "Pink Stripes Peach.png",
    "Pink Stripes.png",
    "Quechquémitl Glow.png",
    "Quechquémitl Light Green.png",
    "Quechquémitl Lime.png",
    "Quechquémitl Pink Sun.png",
    "Quechquémitl Pink.png",
    "Quechquémitl Red.png",
    "Quechquémitl White.png",
    "Queen Dress.png",
    "Red Stripes.png",
    "Serpent Tattoo Black.png",
    "Serpent Tattoo Blue.png",
    "Serpent Tattoo Dark Blue.png",
    "Serpent Tattoo Gold.png",
    "Serpent Tattoo Green.png",
    "Serpent Tattoo Jade.png",
    "Serpent Tattoo Pink.png",
    "Serpent Tattoo Red.png",
    "Serpent Tattoo Turquoise.png",
    "Serpent Tattoo White.png",
    "Simple Dress Blue.png",
    "Simple White.png",
    "Spiral Tattoo Blue.png",
    "Spiral Tattoo Brown.png",
    "Spiral Tattoo Fuchsia.png",
    "Spiral Tuquoise.png",
    "Stripes Tattoo Black.png",
    "Stripes Tattoo Blue.png",
    "Stripes Tattoo Dark Blue.png",
    "Stripes Tattoo Mint.png",
    "Stripes Tattoo Red.png",
    "Stripes Tattoo Sand.png",
    "Stripes Tattoo Violet.png",
    "Stripes Tattoo.png",
    "Tee Blue Sun.png",
    "Tee Orange Sun.png",
    "Tee Pink Sun.png",
    "Tee Red Sun.png",
    "Tee White Wing.png",
    "Tribal Tee Blue.png",
    "Tribal Tee Green.png",
    "Tribal Tee Mint.png",
    "Tribal Tee Pink.png",
    "Tribal Tee Red.png",
    "Tribal Tee Turquoise.png",
    "Tribal Tee White.png",
    "Stripes Tattoo Yellow.png"
  ],
  "Face Paint": [
    "Blaze Blue Pastel.png",
    "Blaze Blue.png",
    "Blaze Brown.png",
    "Blaze Dark Blue.png",
    "Blaze Green Yellow.png",
    "Blaze Green.png",
    "Blaze Grey and Gold.png",
    "Blaze Red.png",
    "Blaze Violet Pastel.png",
    "Blaze Yellow.png",
    "Flare Black.png",
    "Flare Blue.png",
    "Flare Dark Blue.png",
    "Flare Dark Green.png",
    "Flare Dark Turquoise.png",
    "Flare Green.png",
    "Flare Grey.png",
    "Flare Pink.png",
    "Flare Red.png",
    "Flare White Blue.png",
    "Flare White Orange.png",
    "Flare Yellow.png",
    "Floral  Green Stripe.png",
    "Floral Black.png",
    "Floral Blue Stripe.png",
    "Floral Green.png",
    "Floral Light Blue.png",
    "Floral Orange.png",
    "Floral Pink.png",
    "Floral Purple Stripe.png",
    "Floral Red Stripe.png",
    "Floral Red.png",
    "Floral White.png",
    "Floral Yellow.png",
    "Fold Black.png",
    "Fold Blue.png",
    "Fold Gray.png",
    "Fold Green.png",
    "Fold Lavender.png",
    "Fold Light Blue.png",
    "Fold Orange.png",
    "Fold Red.png",
    "Fold Turquoise.png",
    "Fold Yellow.png",
    "Full Face Pink.png",
    "Full Face Turquoise.png",
    "Half Face Black.png",
    "Half Face Blue.png",
    "Half Face Green.png",
    "Half Face Orange.png",
    "Half Face Red.png",
    "Half Face White.png",
    "Half Face Yellow.png",
    "Mark Black.png",
    "Mark Blue.png",
    "Mark Brown.png",
    "Mark Dark Blue.png",
    "Mark Fire.png",
    "Mark Green.png",
    "Mark Light Blue.png",
    "Mark Light Yellow.png",
    "Mark Orange.png",
    "Mark Red.png",
    "None.png",
    "Vertical Black.png",
    "Vertical Blue.png",
    "Vertical Gold.png",
    "Vertical Green.png",
    "Vertical Orange Yellow.png",
    "Vertical Red.png",
    "Vertical White.png",
    "Zigzag Black.png",
    "Zigzag Blue.png",
    "Zigzag Brown.png",
    "Zigzag Green.png",
    "Zigzag Pink.png",
    "Zigzag Red.png",
    "Zigzag Yellow.png",
    "Flare Gold.png",
    "Floral Dark Blue.png",
    "Mark Yellow.png"
  ],
  "Necklace": [
    "Boards Turquoise.png",
    "Bulb Jade.png",
    "Bulb Turquoise.png",
    "Eagle Eyes Jade.png",
    "Eagle Eyes Orange.png",
    "Eagle Eyes Pink.png",
    "Jewels Blue.png",
    "Jewels Obsidian.png",
    "Jewels.png",
    "Leather Mosaic.png",
    "Necklet Jade.png",
    "Necklet Pink.png",
    "Necklet Yellow.png",
    "None.png",
    "Pebble Aquamarine.png",
    "Pebble Obsidian.png",
    "Peebles Light.png",
    "Peebles Pink.png",
    "Queen Purple.png",
    "Queen Silver.png",
    "Queen.png",
    "Rings Adamantine.png",
    "Rings Red.png",
    "Rings.png",
    "Tight Jade Necklace.png",
    "Tight Necklace Cubic.png",
    "Tight Necklace Gold.png",
    "Tight Necklace.png"
  ],
  "Eyes": [
    "Angry Blue Paint Yellow Side.png",
    "Angry Green Front.png",
    "Angry Pink Side.png",
    "Angry Red Paint Turquoise Side.png",
    "Angry Red Side.png",
    "Angry Turquoise Side.png",
    "Attention Blue Paint Blue Front.png",
    "Attention Blue Paint Brown Front.png",
    "Attention Blue Paint Yellow Front.png",
    "Attention Wine Paint Pink Front.png",
    "Cat Blue Side.png",
    "Cat Gray Side.png",
    "Cat Jade Side.png",
    "Cat Red Front.png",
    "Cat Strawberry Side.png",
    "Cat Trippy Side.png",
    "Cat Turquoise Front.png",
    "Cat Yellow Front.png",
    "Cat Yellow Side.png",
    "Fury Blue Front.png",
    "Fury Blue Painted Blue Side.png",
    "Fury Blue Painted Brown Front.png",
    "Fury Blue Painted Green Side.png",
    "Fury Blue Painted Red Side.png",
    "Fury Blue Painted Yellow Side.png",
    "Fury Blue Side.png",
    "Fury Green Front.png",
    "Fury Green Painted Blue Side.png",
    "Fury Pink Painted brown Side.png",
    "Fury Purple Painted Front.png",
    "Fury Red Front.png",
    "Fury Red Side.png",
    "Fury Side Green.png",
    "Fury Turquoise Side.png",
    "Fury Wine Painted Orange Side.png",
    "Fury Yellow Side.png",
    "Happy BGreen Double Paint.png",
    "Happy Blue Paint.png",
    "Happy Double Pink Paint.png",
    "Happy Red Paint.png",
    "Happy.png",
    "Midst Blue Side.png",
    "Midst Brown Side.png",
    "Midst Green Paint Green Front.png",
    "Midst Green Side.png",
    "Midst Pink Paint Green Side.png",
    "Midst Red Paint Blue Side.png",
    "Midst Red Paint Brown Front.png",
    "Midst Red Paint Green Side.png",
    "Midst Red Paint Yellow Side.png",
    "Midst Red Side.png",
    "Midst Turquoise Side.png",
    "Midst Violet Paint Front.png",
    "Rounded Blue Front.png",
    "Rounded Gray Paint Front.png",
    "Rounded Pink Green Paint Front.png",
    "Rounded Red Blue Paint Front.png",
    "Rounded Red Front.png",
    "Rounded Sand Jade Paint Front.png",
    "Rounded Turquoise Blue Paint Front.png",
    "Rounded Turquoise Front.png",
    "Rounded Violet Paint  Front.png",
    "Shy Blue Purple Paint Side.png",
    "Shy Blue Red Paint Side.png",
    "Shy Brown Side.png",
    "Shy Dark Blue Paint Side.png",
    "Shy Gold Paint Side.png",
    "Shy Green Side.png",
    "Shy Light Blue Side.png",
    "Shy Pink Paint Side.png",
    "Shy Red Paint Side.png",
    "Shy Turquoise Red Paint Side.png",
    "Shy Yellow Side.png",
    "Suprised Blue Paint Yellow Side.png",
    "Suprised Purple Side.png",
    "Suprised Red Paint Blue Side.png",
    "Suprised Red Side.png",
    "Suprised Turquoise Side.png",
    "Triangle Blue Paint Red Front.png",
    "Triangle Blue Paint Turquoise Front.png",
    "Triangle Blue Paint Yellow Side.png",
    "Triangle Gold Paint Purple Front.png",
    "Triangle Purple Paint Green Side.png",
    "Triangle Red Paint Blue Side.png",
    "Triangle Red Paint Yellow Side.png",
    "serious yellow side.png",
    "Angry Blue Paint Turquoise Side.png",
    "Cat Trippy Front.png",
    "Shy Blue Side.png",
    "Triangle Green Paint Green Front.png"
  ],
  "Mouth": [
    "Angry Black.png",
    "Angry Green.png",
    "Angry Pink.png",
    "Angry Red.png",
    "Angry Turquoise.png",
    "Angry.png",
    "Cunning.png",
    "Happy Vampire Blue.png",
    "Happy Vampire Gray.png",
    "Happy Vampire Green.png",
    "Happy Vampire Naked.png",
    "Happy Vampire Pink.png",
    "Happy Vampire Red.png",
    "Happy Vampire Yellow.png",
    "Laughing Black.png",
    "Laughing Real Blue.png",
    "Laughing Real Green.png",
    "Laughing Real Pink.png",
    "Laughing.png",
    "Lined Mouth.png",
    "Neko Black.png",
    "Neko Green.png",
    "Neko Pink.png",
    "Neko.png",
    "Open Blue.png",
    "Open Real Pink.png",
    "Open Real Purple.png",
    "Open Red.png",
    "Open.png",
    "Ordinary Black.png",
    "Ordinary Blue.png",
    "Ordinary Mint.png",
    "Ordinary Red.png",
    "Ordinary.png",
    "Regular.png",
    "Rogue.png",
    "Serious Black.png",
    "Serious Red.png",
    "Serious.png",
    "Small Blue.png",
    "Small Red.png",
    "Small.png",
    "Smile Black.png",
    "Smile Blue.png",
    "Smile Red.png",
    "Smile.png",
    "Vampire Black.png",
    "Vampire Blue.png",
    "Vampire Naked.png",
    "Vampire Red.png"
  ],
  "Hair": [
    "Bangs Black.png",
    "Bangs Blonde.png",
    "Bangs Blue.png",
    "Bangs Brown.png",
    "Bangs Green.png",
    "Bangs Pink.png",
    "Bangs Ponytail Black.png",
    "Bangs Ponytail Blue.png",
    "Bangs Ponytail Green.png",
    "Bangs Ponytail Pink.png",
    "Bangs Ponytail Purple.png",
    "Bangs Ponytail Red.png",
    "Bangs Ponytail White.png",
    "Bangs Red.png",
    "Blowout Blonde.png",
    "Blowout Blue.png",
    "Blowout Dark.png",
    "Blowout Green.png",
    "Blowout Red.png",
    "Bob Black.png",
    "Bob Blonde.png",
    "Bob Blue.png",
    "Bob Brown.png",
    "Bob Green.png",
    "Bob Pink.png",
    "Bob Red.png",
    "Bob Silver.png",
    "Braid Black.png",
    "Braid Brown.png",
    "Braid Pink.png",
    "Braid Red.png",
    "Braid White.png",
    "Braid Yellow.png",
    "Crown Braid Black.png",
    "Crown Braid Blonde.png",
    "Crown Braid Blue.png",
    "Crown Braid Brown.png",
    "Crown Braid Green.png",
    "Crown Braid Pink.png",
    "Crown Braid Reed.png",
    "Crown Braid Silver.png",
    "Ponytail Black.png",
    "Ponytail Blonde.png",
    "Ponytail Blue.png",
    "Ponytail Brown.png",
    "Ponytail Pink.png",
    "Ponytail Red.png",
    "Ponytail Silver.png",
    "Short Black.png",
    "Short Blonde.png",
    "Short Brown.png",
    "Short Pink.png",
    "Short Red.png",
    "Short Silver.png",
    "Wavy Black.png",
    "Wavy Blonde.png",
    "Wavy Blue.png",
    "Wavy Brown.png",
    "Wavy Green.png",
    "Wavy Pink.png",
    "Wavy Red.png",
    "Wavy Silver.png",
    "Blowout Dark Blue.png"
  ],
  "Earring": [
    "Balls Tourmaline.png",
    "Balls.png",
    "Big Purple Feather.png",
    "Climber.png",
    "Duck Fluorite.png",
    "Duck Gold.png",
    "Duck Rubi.png",
    "Feather Pink.png",
    "Feather Red.png",
    "Feather Yellow.png",
    "Gold and Turquoise Disc.png",
    "Half Moon Gold.png",
    "Half Moon Jade.png",
    "HumminBird Pink.png",
    "HummingBird Blue.png",
    "HummingBird Green.png",
    "HummingBird Purple.png",
    "HummingBird White.png",
    "Leather Gold Ring.png",
    "Leather Ring.png",
    "Long Feather Fire.png",
    "Long Feather Purple.png",
    "Long Feather Teal.png",
    "None.png",
    "Pend Vio Blue.png",
    "Stones Jade.png",
    "Stones Obsidian.png",
    "Stones River.png",
    "Tip.png",
    "Canine Obsidian.png",
    "Duck Ivory.png",
    "Duck Obsidian.png",
    "Set Golden.png",
    "Set Obsidian.png",
    "Stones Rubi.png"
  ],
  "Mask": [
    "Bear Blue.png",
    "Bear Brown.png",
    "Bear Dreamer.png",
    "Bear Fury.png",
    "Bear White.png",
    "Birdie Green.png",
    "Birdie Red.png",
    "Birdie White.png",
    "Birdy Blue.png",
    "Diadem Green.png",
    "Diadem Pink.png",
    "Diadem Purple.png",
    "Diadem Red.png",
    "Diadem White.png",
    "Dog Black.png",
    "Dog Brown.png",
    "Dog Green.png",
    "Dog Light Blue.png",
    "Dog Pink.png",
    "Dog White.png",
    "Eagle Blue Gold.png",
    "Eagle Blue Green.png",
    "Eagle Blue.png",
    "Eagle Dark Orange.png",
    "Eagle Lime.png",
    "Eagle Matte Blue.png",
    "Eagle Orange.png",
    "Eagle Pink.png",
    "Eagle Red.png",
    "Eagle Violet.png",
    "Eagle white.png",
    "Explorer Blue.png",
    "Explorer Purple.png",
    "Explorer Red.png",
    "Explorer Yellow.png",
    "Gator Blue.png",
    "Gator Dark Green.png",
    "Gator Gold.png",
    "Gator Green.png",
    "Gator Violet.png",
    "Gator White.png",
    "Hare Blue.png",
    "Hare Gold.png",
    "Hare Green.png",
    "Hare Red.png",
    "Hare White.png",
    "Jaguar Blue.png",
    "Jaguar Brown Blue.png",
    "Jaguar Dark Blue.png",
    "Jaguar Green.png",
    "Jaguar Pink.png",
    "Jaguar Red Green.png",
    "Jaguar Violet.png",
    "Jaguar White Blue.png",
    "Jaguar White Red.png",
    "Jaguar Yellow Blue.png",
    "Jaguar Yellow Green.png",
    "Jaguar Yellow Red.png",
    "Owl Blue.png",
    "placeholder",
    "Owl Bright.png",
    "Owl Brown.png",
    "Owl Gray.png",
    "Owl Green Red.png",
    "Owl Green.png",
    "Owl Pink.png",
    "Owl Red.png",
    "Owl Turquoise.png",
    "Owl White Blue.png",
    "Owl White.png",
    "Owl test.png",
    "Parrot Blue.png",
    "Parrot Green.png",
    "Parrot Orange.png",
    "Parrot Pink.png",
    "Parrot Purple.png",
    "Parrot Red.png",
    "Parrot Turquoise.png",
    "Queen Blue.png",
    "Queen Green.png",
    "Queen Light Blue.png",
    "Queen Pink.png",
    "Queen Red.png",
    "Rabbit Brown Blue.png",
    "Rabbit Brown Brown.png",
    "Rabbit Brown Green.png",
    "Rabbit Dark Blue.png",
    "Rabbit Dark Green Red Eyes.png",
    "Rabbit Dark Red.png",
    "Rabbit Gray.png",
    "Rabbit Green.png",
    "Rabbit Pink Purple.png",
    "Rabbit Red Blue.png",
    "Rabbit Violet.png",
    "Rabbit White Blue.png",
    "Rare Mosaic Blue.png",
    "Rare Mosaic.png",
    "Serpent Blue.png",
    "Serpent Dark Blue.png",
    "Serpent Jade.png",
    "Serpent Light Green.png",
    "Serpent Purple.png",
    "Serpent Red.png",
    "Serpent Turquoise.png",
    "Serpent White.png",
    "Warrior Blue.png",
    "Warrior Golden.png",
    "Warrior Green.png",
    "Warrior Jade.png",
    "Warrior Red.png",
    "Warrior Violet.png",
    "Diadem Rainbow.png",
    "Owl Blue Orange.png",
    "Rare Mosaic Gold.png"
  ]
}
export const femaleNoMaskedOG = {
  "Background": [
    "Aqua.png",
    "Aristocracy.png",
    "Bamboo Gradient.png",
    "Bamboo Purple.png",
    "Bamboo Red.png",
    "Bamboo Tropic.png",
    "Black Hole.png",
    "Bubbles Blue.png",
    "Bubbles Pink.png",
    "Calendar Lilac.png",
    "Calendar Ruby.png",
    "Calendar Violet.png",
    "Celeste.png",
    "Double Moons Cloud.png",
    "Double Moons Dark Blue.png",
    "Double Moons Fire.png",
    "Double Moons Mint.png",
    "Double Moons Yellow.png",
    "Fire.png",
    "Flowers Blue.png",
    "Flowers Grey.png",
    "Flowers Middle Green.png",
    "Forest.png",
    "Gators dark.png",
    "Gradient Blue.png",
    "Gradient Gold.png",
    "Gradient Green.png",
    "Gradient Pink.png",
    "Gradient Purple.png",
    "Gradient Red.png",
    "J_Toons.png",
    "Lavender.png",
    "Leaf Glow.png",
    "Leaf Violet.png",
    "Lilac.png",
    "Lines.png",
    "Marble Blue.png",
    "Marble Malva.png",
    "Marble Pink.png",
    "Mint.png",
    "Mosaic Lilac.png",
    "Pastel Cloud.png",
    "Pink Vector.png",
    "Pyramid Azure.png",
    "Pyramid Dark Blue.png",
    "Pyramid Dark Green.png",
    "Pyramid Dark Pink.png",
    "Pyramid Sunrise.png",
    "Real Pastel.png",
    "Red Vector.png",
    "Ring Glow Pink.png",
    "Ring Mint.png",
    "Sand.png",
    "Skulls Contrast.png",
    "Skulls Dark.png",
    "Skulls Neon.png",
    "Skulls Orange.png",
    "Solid Green.png",
    "Solid Wine.png",
    "Stone Blue.png",
    "Stone Gold.png",
    "Stone Jade.png",
    "Stone Orange.png",
    "Stone Purple.png",
    "Stone Sand.png",
    "Stone Turqoise.png",
    "Sun All Red.png",
    "Sun Gold.png",
    "Sun Yellow.png",
    "Yellow.png",
    "Bubbles Green.png",
    "Double Moons Dark Orange.png",
    "Skulls Black.png",
    "Skulls Red.png",
    "Sun Orange.png"
  ],
  "Body": [
    "Blue.png",
    "Chestnut.png",
    "Green.png",
    "Honey.png",
    "Porcelain.png",
    "Red.png",
    "Siena.png",
    "Warm Ivory.png"
  ],
  "Dress": [
    "Feathers Blue.png",
    "Feathers Bright Green.png",
    "Feathers Green.png",
    "Feathers Orange.png",
    "Feathers Pink.png",
    "Fringes Black.png",
    "Fringes Blue.png",
    "Fringes Fluor.png",
    "Fringes Green.png",
    "Fringes Orange.png",
    "Fringes Pink.png",
    "Fringes Purple.png",
    "Fringes Red.png",
    "Fringes Yellow.png",
    "Jewel Blue.png",
    "Jewel Brown.png",
    "Jewel Flowers Blue.png",
    "Jewel Flowers Violet.png",
    "Jewel Flowers.png",
    "Jewel Red.png",
    "Jewel Turquoise.png",
    "Pattern Dress.png",
    "Pattern Tattoo Turquoise.png",
    "Pink Stripes Blue.png",
    "Pink Stripes Peach.png",
    "Pink Stripes.png",
    "Quechquémitl Glow.png",
    "Quechquémitl Light Green.png",
    "Quechquémitl Lime.png",
    "Quechquémitl Pink Sun.png",
    "Quechquémitl Pink.png",
    "Quechquémitl Red.png",
    "Quechquémitl White.png",
    "Queen Dress.png",
    "Red Stripes.png",
    "Serpent Tattoo Black.png",
    "Serpent Tattoo Blue.png",
    "Serpent Tattoo Dark Blue.png",
    "Serpent Tattoo Gold.png",
    "Serpent Tattoo Green.png",
    "Serpent Tattoo Jade.png",
    "Serpent Tattoo Pink.png",
    "Serpent Tattoo Red.png",
    "Serpent Tattoo Turquoise.png",
    "Serpent Tattoo White.png",
    "Simple Dress Blue.png",
    "Simple White.png",
    "Spiral Tattoo Blue.png",
    "Spiral Tattoo Brown.png",
    "Spiral Tattoo Fuchsia.png",
    "Spiral Tuquoise.png",
    "Stripes Tattoo Black.png",
    "Stripes Tattoo Blue.png",
    "Stripes Tattoo Dark Blue.png",
    "Stripes Tattoo Mint.png",
    "Stripes Tattoo Red.png",
    "Stripes Tattoo Sand.png",
    "Stripes Tattoo Violet.png",
    "Stripes Tattoo.png",
    "Tee Blue Sun.png",
    "Tee Orange Sun.png",
    "Tee Pink Sun.png",
    "Tee Red Sun.png",
    "Tee White Wing.png",
    "Tribal Tee Blue.png",
    "Tribal Tee Green.png",
    "Tribal Tee Mint.png",
    "Tribal Tee Pink.png",
    "Tribal Tee Red.png",
    "Tribal Tee Turquoise.png",
    "Tribal Tee White.png",
    "Stripes Tattoo Yellow.png"
  ],
  "Face Paint": [
    "Blaze Blue Pastel.png",
    "Blaze Blue.png",
    "Blaze Brown.png",
    "Blaze Dark Blue.png",
    "Blaze Green Yellow.png",
    "Blaze Green.png",
    "Blaze Grey and Gold.png",
    "Blaze Red.png",
    "Blaze Violet Pastel.png",
    "Blaze Yellow.png",
    "Flare Black.png",
    "Flare Blue.png",
    "Flare Dark Blue.png",
    "Flare Dark Green.png",
    "Flare Dark Turquoise.png",
    "Flare Green.png",
    "Flare Grey.png",
    "Flare Pink.png",
    "Flare Red.png",
    "Flare White Blue.png",
    "Flare White Orange.png",
    "Flare Yellow.png",
    "Floral  Green Stripe.png",
    "Floral Black.png",
    "Floral Blue Stripe.png",
    "Floral Green.png",
    "Floral Light Blue.png",
    "Floral Orange.png",
    "Floral Pink.png",
    "Floral Purple Stripe.png",
    "Floral Red Stripe.png",
    "Floral Red.png",
    "Floral White.png",
    "Floral Yellow.png",
    "Fold Black.png",
    "Fold Blue.png",
    "Fold Gray.png",
    "Fold Green.png",
    "Fold Lavender.png",
    "Fold Light Blue.png",
    "Fold Orange.png",
    "Fold Red.png",
    "Fold Turquoise.png",
    "Fold Yellow.png",
    "Full Face Pink.png",
    "Full Face Turquoise.png",
    "Half Face Black.png",
    "Half Face Blue.png",
    "Half Face Green.png",
    "Half Face Orange.png",
    "Half Face Red.png",
    "Half Face White.png",
    "Half Face Yellow.png",
    "Mark Black.png",
    "Mark Blue.png",
    "Mark Brown.png",
    "Mark Dark Blue.png",
    "Mark Fire.png",
    "Mark Green.png",
    "Mark Light Blue.png",
    "Mark Light Yellow.png",
    "Mark Orange.png",
    "Mark Red.png",
    "None.png",
    "Vertical Black.png",
    "Vertical Blue.png",
    "Vertical Gold.png",
    "Vertical Green.png",
    "Vertical Orange Yellow.png",
    "Vertical Red.png",
    "Vertical White.png",
    "Zigzag Black.png",
    "Zigzag Blue.png",
    "Zigzag Brown.png",
    "Zigzag Green.png",
    "Zigzag Pink.png",
    "Zigzag Red.png",
    "Zigzag Yellow.png",
    "Flare Gold.png",
    "Floral Dark Blue.png",
    "Mark Yellow.png"
  ],
  "Necklace": [
    "Boards Turquoise.png",
    "Bulb Jade.png",
    "Bulb Turquoise.png",
    "Eagle Eyes Jade.png",
    "Eagle Eyes Orange.png",
    "Eagle Eyes Pink.png",
    "Jewels Blue.png",
    "Jewels Obsidian.png",
    "Jewels.png",
    "Leather Mosaic.png",
    "Necklet Jade.png",
    "Necklet Pink.png",
    "Necklet Yellow.png",
    "None.png",
    "Pebble Aquamarine.png",
    "Pebble Obsidian.png",
    "Peebles Light.png",
    "Peebles Pink.png",
    "Queen Purple.png",
    "Queen Silver.png",
    "Queen.png",
    "Rings Adamantine.png",
    "Rings Red.png",
    "Rings.png",
    "Tight Jade Necklace.png",
    "Tight Necklace Cubic.png",
    "Tight Necklace Gold.png",
    "Tight Necklace.png"
  ],
  "Eyes": [
    "Angry Blue Paint Yellow Side.png",
    "Angry Green Front.png",
    "Angry Pink Side.png",
    "Angry Red Paint Turquoise Side.png",
    "Angry Red Side.png",
    "Angry Turquoise Side.png",
    "Attention Blue Paint Blue Front.png",
    "Attention Blue Paint Brown Front.png",
    "Attention Blue Paint Yellow Front.png",
    "Attention Wine Paint Pink Front.png",
    "Cat Blue Side.png",
    "Cat Gray Side.png",
    "Cat Jade Side.png",
    "Cat Red Front.png",
    "Cat Strawberry Side.png",
    "Cat Trippy Side.png",
    "Cat Turquoise Front.png",
    "Cat Yellow Front.png",
    "Cat Yellow Side.png",
    "Fury Blue Front.png",
    "Fury Blue Painted Blue Side.png",
    "Fury Blue Painted Brown Front.png",
    "Fury Blue Painted Green Side.png",
    "Fury Blue Painted Red Side.png",
    "Fury Blue Painted Yellow Side.png",
    "Fury Blue Side.png",
    "Fury Green Front.png",
    "Fury Green Painted Blue Side.png",
    "Fury Pink Painted brown Side.png",
    "Fury Purple Painted Front.png",
    "Fury Red Front.png",
    "Fury Red Side.png",
    "Fury Side Green.png",
    "Fury Turquoise Side.png",
    "Fury Wine Painted Orange Side.png",
    "Fury Yellow Side.png",
    "Happy BGreen Double Paint.png",
    "Happy Blue Paint.png",
    "Happy Double Pink Paint.png",
    "Happy Red Paint.png",
    "Happy.png",
    "Midst Blue Side.png",
    "Midst Brown Side.png",
    "Midst Green Paint Green Front.png",
    "Midst Green Side.png",
    "Midst Pink Paint Green Side.png",
    "Midst Red Paint Blue Side.png",
    "Midst Red Paint Brown Front.png",
    "Midst Red Paint Green Side.png",
    "Midst Red Paint Yellow Side.png",
    "Midst Red Side.png",
    "Midst Turquoise Side.png",
    "Midst Violet Paint Front.png",
    "Rounded Blue Front.png",
    "Rounded Gray Paint Front.png",
    "Rounded Pink Green Paint Front.png",
    "Rounded Red Blue Paint Front.png",
    "Rounded Red Front.png",
    "Rounded Sand Jade Paint Front.png",
    "Rounded Turquoise Blue Paint Front.png",
    "Rounded Turquoise Front.png",
    "Rounded Violet Paint  Front.png",
    "Shy Blue Purple Paint Side.png",
    "Shy Blue Red Paint Side.png",
    "Shy Brown Side.png",
    "Shy Dark Blue Paint Side.png",
    "Shy Gold Paint Side.png",
    "Shy Green Side.png",
    "Shy Light Blue Side.png",
    "Shy Pink Paint Side.png",
    "Shy Red Paint Side.png",
    "Shy Turquoise Red Paint Side.png",
    "Shy Yellow Side.png",
    "Suprised Blue Paint Yellow Side.png",
    "Suprised Purple Side.png",
    "Suprised Red Paint Blue Side.png",
    "Suprised Red Side.png",
    "Suprised Turquoise Side.png",
    "Triangle Blue Paint Red Front.png",
    "Triangle Blue Paint Turquoise Front.png",
    "Triangle Blue Paint Yellow Side.png",
    "Triangle Gold Paint Purple Front.png",
    "Triangle Purple Paint Green Side.png",
    "Triangle Red Paint Blue Side.png",
    "Triangle Red Paint Yellow Side.png",
    "serious yellow side.png",
    "Angry Blue Paint Turquoise Side.png",
    "Cat Trippy Front.png",
    "Shy Blue Side.png",
    "Triangle Green Paint Green Front.png"
  ],
  "Mouth": [
    "Angry Black.png",
    "Angry Green.png",
    "Angry Pink.png",
    "Angry Red.png",
    "Angry Turquoise.png",
    "Angry.png",
    "Cunning.png",
    "Happy Vampire Blue.png",
    "Happy Vampire Gray.png",
    "Happy Vampire Green.png",
    "Happy Vampire Naked.png",
    "Happy Vampire Pink.png",
    "Happy Vampire Red.png",
    "Happy Vampire Yellow.png",
    "Laughing Black.png",
    "Laughing Real Blue.png",
    "Laughing Real Green.png",
    "Laughing Real Pink.png",
    "Laughing.png",
    "Lined Mouth.png",
    "Neko Black.png",
    "Neko Green.png",
    "Neko Pink.png",
    "Neko.png",
    "Open Blue.png",
    "Open Real Pink.png",
    "Open Real Purple.png",
    "Open Red.png",
    "Open.png",
    "Ordinary Black.png",
    "Ordinary Blue.png",
    "Ordinary Mint.png",
    "Ordinary Red.png",
    "Ordinary.png",
    "Regular.png",
    "Rogue.png",
    "Serious Black.png",
    "Serious Red.png",
    "Serious.png",
    "Small Blue.png",
    "Small Red.png",
    "Small.png",
    "Smile Black.png",
    "Smile Blue.png",
    "Smile Red.png",
    "Smile.png",
    "Vampire Black.png",
    "Vampire Blue.png",
    "Vampire Naked.png",
    "Vampire Red.png"
  ],
  "Hair": [
    "Bangs Black.png",
    "Bangs Blonde.png",
    "Bangs Blue.png",
    "Bangs Brown.png",
    "Bangs Green.png",
    "Bangs Pink.png",
    "Bangs Ponytail Black.png",
    "Bangs Ponytail Blue.png",
    "Bangs Ponytail Green.png",
    "Bangs Ponytail Pink.png",
    "Bangs Ponytail Purple.png",
    "Bangs Ponytail Red.png",
    "Bangs Ponytail White.png",
    "Bangs Red.png",
    "Blowout Black.png",
    "Blowout Blonde.png",
    "Blowout Blue.png",
    "Blowout Fire.png",
    "Blowout Green.png",
    "Blowout Red.png",
    "Blowout Silver.png",
    "Bob Black.png",
    "Bob Blonde.png",
    "Bob Blue.png",
    "Bob Brown.png",
    "Bob Green.png",
    "Bob Pink.png",
    "Bob Red.png",
    "Bob Silver.png",
    "Braid Black.png",
    "Braid Brown.png",
    "Braid Pink.png",
    "Braid Red.png",
    "Braid White.png",
    "Braid Yellow.png",
    "Crown Braid Black.png",
    "Crown Braid Blonde.png",
    "Crown Braid Blue.png",
    "Crown Braid Brown.png",
    "Crown Braid Feathers.png",
    "Crown Braid Green.png",
    "Crown Braid Pink.png",
    "Crown Braid Reed.png",
    "Crown Braid Silver.png",
    "Crown Gold Feathers.png",
    "Faux Hawk Black.png",
    "Faux Hawk Blonde.png",
    "Faux Hawk Blue.png",
    "Faux Hawk Green.png",
    "Faux Hawk Pink.png",
    "Faux Hawk Red.png",
    "Faux Hawk Silver.png",
    "Faux Hawk Violet.png",
    "Liberty Spikes Blonde.png",
    "Liberty Spikes Blue.png",
    "Liberty Spikes Green.png",
    "Liberty Spikes Pink.png",
    "Liberty Spikes White.png",
    "Long Black Shaved Side.png",
    "Long Blonde Shaved Side.png",
    "Long Blue Shaved Side.png",
    "Long Brown Shaved Side.png",
    "Long Green Shaved Side.png",
    "Long Pink Shaved Side.png",
    "Long Red Shaved Side.png",
    "Long Silver Shaved Side.png",
    "Ponytail Black.png",
    "Ponytail Blonde.png",
    "Ponytail Blue.png",
    "Ponytail Brown.png",
    "Ponytail Pink.png",
    "Ponytail Red.png",
    "Ponytail Silver.png",
    "Punky Black.png",
    "Punky Blonde.png",
    "Punky Blue.png",
    "Punky Gray.png",
    "Punky Green.png",
    "Punky Light.png",
    "Punky Pink.png",
    "Punky Red.png",
    "Short Black.png",
    "Short Blonde.png",
    "Short Brown.png",
    "Short Pink.png",
    "Short Red.png",
    "Short Silver.png",
    "Two Buns Black.png",
    "Two Buns Blonde.png",
    "Two Buns Blue.png",
    "Two Buns Brown.png",
    "Two Buns Pink.png",
    "Two Buns Red.png",
    "Two Buns Silver.png",
    "Wavy Black.png",
    "Wavy Blonde.png",
    "Wavy Blue.png",
    "Wavy Brown.png",
    "Wavy Green.png",
    "Wavy Pink.png",
    "Wavy Red.png",
    "Wavy Silver.png",
    "Blowout Pink.png",
    "Blowout Purple.png"
  ],
  "Earring": [
    "Balls Tourmaline.png",
    "Balls.png",
    "Big Purple Feather.png",
    "Climber.png",
    "Duck Fluorite.png",
    "Duck Gold.png",
    "Duck Rubi.png",
    "Feather Pink.png",
    "Feather Red.png",
    "Feather Yellow.png",
    "Gold and Turquoise Disc.png",
    "Half Moon Gold.png",
    "Half Moon Jade.png",
    "HumminBird Pink.png",
    "HummingBird Blue.png",
    "HummingBird Green.png",
    "HummingBird Purple.png",
    "HummingBird White.png",
    "Leather Gold Ring.png",
    "Leather Ring.png",
    "Long Feather Fire.png",
    "Long Feather Purple.png",
    "Long Feather Teal.png",
    "None.png",
    "Pend Vio Blue.png",
    "Stones Jade.png",
    "Stones Obsidian.png",
    "Stones River.png",
    "Tip.png",
    "Canine Obsidian.png",
    "Duck Ivory.png",
    "Duck Obsidian.png",
    "Set Golden.png",
    "Set Obsidian.png",
    "Stones Rubi.png"
  ],
  "Mask": [
    "None.png"
  ]
}
export const maleMaskedOG = {
  "Background": [
    "Aqua.png",
    "Aristocracy.png",
    "Bamboo Gradient.png",
    "Bamboo Purple.png",
    "Bamboo Red.png",
    "Bamboo Tropic.png",
    "Black Hole.png",
    "Bubbles Blue.png",
    "Bubbles Pink.png",
    "Calendar Lilac.png",
    "Calendar Ruby.png",
    "Calendar Violet.png",
    "Celeste.png",
    "Double Moons Cloud.png",
    "Double Moons Dark Blue.png",
    "Double Moons Fire.png",
    "Double Moons Mint.png",
    "Double Moons Yellow.png",
    "Fire.png",
    "Flowers Blue.png",
    "Flowers Grey.png",
    "Flowers Middle Green.png",
    "Forest.png",
    "Gators dark.png",
    "Gradient Blue.png",
    "Gradient Gold.png",
    "Gradient Green.png",
    "Gradient Pink.png",
    "Gradient Purple.png",
    "Gradient Red.png",
    "J_Toons.png",
    "Lavender.png",
    "Leaf Glow.png",
    "Leaf Violet.png",
    "Lilac.png",
    "Lines.png",
    "Marble Blue.png",
    "Marble Malva.png",
    "Marble Pink.png",
    "Mint.png",
    "Mosaic Lilac.png",
    "Pastel Cloud.png",
    "Pink Vector.png",
    "Pyramid Azure.png",
    "Pyramid Dark Blue.png",
    "Pyramid Dark Green.png",
    "Pyramid Dark Pink.png",
    "Pyramid Sunrise.png",
    "Real Pastel.png",
    "Red Vector.png",
    "Ring Glow Pink.png",
    "Ring Mint.png",
    "Sand.png",
    "Skulls Contrast.png",
    "Skulls Dark.png",
    "Skulls Neon.png",
    "Skulls Orange.png",
    "Solid Green.png",
    "Solid Wine.png",
    "Stone Blue.png",
    "Stone Gold.png",
    "Stone Jade.png",
    "Stone Orange.png",
    "Stone Purple.png",
    "Stone Sand.png",
    "Stone Turqoise.png",
    "Sun All Red.png",
    "Sun Gold.png",
    "Sun Yellow.png",
    "Yellow.png",
    "Bubbles Green.png",
    "Double Moons Dark Orange.png",
    "Skulls Black.png",
    "Skulls Red.png",
    "Sun Orange.png"
  ],
  "Body": [
    "Blue.png",
    "Chestnut.png",
    "DoD OG.png",
    "Green.png",
    "Honey.png",
    "Porcelain.png",
    "Red.png",
    "Siena.png",
    "Warm Ivory.png"
  ],
  "Dress": [
    "Body Paint Blue.png",
    "Body Paint Dark Green.png",
    "Body Paint Dark.png",
    "Body Paint Fire.png",
    "Body Paint Jade.png",
    "Body Paint Light Green.png",
    "Body Paint Purple.png",
    "Body Paint Red.png",
    "Pattern Tattoo Black.png",
    "Pattern Tattoo Blue.png",
    "Pattern Tattoo DoD.png",
    "Pattern Tattoo Full White.png",
    "Pattern Tattoo Green.png",
    "Pattern Tattoo Red.png",
    "Pattern Tattoo Turquoise.png",
    "Quechquémitl Black.png",
    "Quechquémitl Gold.png",
    "Quechquémitl Gray.png",
    "Quechquémitl Green.png",
    "Quechquémitl Lime.png",
    "Quechquémitl Purple.png",
    "Quechquémitl Turquoise.png",
    "Quechquémitl White.png",
    "Rainbow Body Paint.png",
    "Stripes Tattoo Blue.png",
    "Stripes Tattoo Brown.png",
    "Stripes Tattoo Dark Green.png",
    "Stripes Tattoo Gray.png",
    "Stripes Tattoo Light Blue.png",
    "Stripes Tattoo Light Green.png",
    "Stripes Tattoo Red.png",
    "Stripes Tattoo White.png",
    "Stripes Tattoo Yellow.png",
    "Sun Tattoo Black Tee.png",
    "Sun Tattoo Blue Tee.png",
    "Sun Tattoo Coral.png",
    "Sun Tattoo Green Tee.png",
    "Sun Tattoo Mint Tee.png",
    "Sun Tattoo Orange Tee.png",
    "Sun Tattoo Red Tee.png",
    "Sun Tee Grey.png",
    "Sun Tee.png",
    "Tee Green.png",
    "Tee Turquoise.png",
    "Tee.png",
    "Triangles Tattoo Blue.png",
    "Triangles Tattoo Bright Red.png",
    "Triangles Tattoo Dark Green.png",
    "Triangles Tattoo Green.png",
    "Triangles Tattoo Orange.png",
    "Triangles Tattoo Red.png",
    "Triangles Tattoo Sky.png",
    "Triangles Tattoo White.png",
    "Triangles Tattoo Yellow.png",
    "Tribal Blue.png",
    "Tribal Full Body Black.png",
    "Tribal Full Body Blue.png",
    "Tribal Full Body Dark Blue.png",
    "Tribal Full Body Gold.png",
    "Tribal Full Body Red.png",
    "Tribal Full Body White.png",
    "Tribal Full Body.png",
    "Tribal Red.png",
    "Tribal Tee Black.png",
    "Tribal Tee Blue.png",
    "Tribal Tee Gray.png",
    "Tribal Tee Green.png",
    "Tribal Tee Purple.png",
    "Tribal Tee Red.png",
    "Tribal Tee Sand.png",
    "Tribal Tee White.png",
    "Tribal Tee Yellow.png"
  ],
  "Face Paint": [
    "Armour Copper.png",
    "Armour Gold.png",
    "Armour Jade.png",
    "Armour Obsidian.png",
    "Blaze Blue Pastel.png",
    "Blaze Blue.png",
    "Blaze Brown.png",
    "Blaze Dark Blue.png",
    "Blaze Green Yellow.png",
    "Blaze Green.png",
    "Blaze Grey and Gold.png",
    "Blaze Red.png",
    "Blaze Violet Pastel.png",
    "Blaze Yellow.png",
    "Flare Black.png",
    "Flare Blue.png",
    "Flare Dark Blue.png",
    "Flare Dark Green.png",
    "Flare Dark Turquoise.png",
    "Flare Green.png",
    "Flare Grey.png",
    "Flare Pink.png",
    "Flare Red.png",
    "Flare White Blue.png",
    "Flare White Orange.png",
    "Flare Yellow.png",
    "Fold Black.png",
    "Fold Blue.png",
    "Fold Gray.png",
    "Fold Green.png",
    "Fold Light Blue.png",
    "Fold Light Red.png",
    "Fold Orange.png",
    "Fold Red.png",
    "Fold Turquoise.png",
    "Fold Yellow.png",
    "Full Face Black.png",
    "Full Face Blue.png",
    "Full Face Gold.png",
    "Full Face Light Red.png",
    "Full Face Orange.png",
    "Full Face Red.png",
    "Full Face White.png",
    "Half Face Simple Black.png",
    "Half Face Simple Blue Violet.png",
    "Half Face Simple Blue.png",
    "Half Face Simple Green.png",
    "Half Face Simple Light Blue.png",
    "Half Face Simple Orange.png",
    "Half Face Simple Red.png",
    "Half Face Simple Turquoise.png",
    "Half Face Simple Yellow.png",
    "Mark Black.png",
    "Mark Blue.png",
    "Mark Brown.png",
    "Mark Dark Blue.png",
    "Mark Fire.png",
    "Mark Green.png",
    "Mark Light Blue.png",
    "Mark Light Yellow.png",
    "Mark Orange.png",
    "Mark Red.png",
    "None.png",
    "Zigzag Black.png",
    "Zigzag Blue.png",
    "Zigzag Brown.png",
    "Zigzag Green.png",
    "Zigzag Red.png",
    "Zigzag Yellow.png",
    "Flare Gold.png",
    "Full Face Green.png",
    "Mark Yellow.png"
  ],
  "Necklace": [
    "Armour Copper.png",
    "Armour Gold.png",
    "Armour Jade.png",
    "Armour Obsidian.png",
    "Board Side Ivory.png",
    "Boards Gold.png",
    "Boards Ivory.png",
    "Boards Jade.png",
    "Boards Obsidian.png",
    "placeholder",
    "Boards Rubi.png",
    "Boards Side Gold.png",
    "Boards Turquoise.png",
    "Bulb Gold.png",
    "Bulb Jade.png",
    "Bulb Turquoisee.png",
    "Demon Tattoo Black.png",
    "Demon Tattoo Red.png",
    "Demon Tattoo Turquoise.png",
    "Demon Tattoo White.png",
    "King Lapis Lazuli.png",
    "King Rubii.png",
    "King.png",
    "Leather Mosaic Blue.png",
    "Leather Mosaic Grey.png",
    "Necklet Blue.png",
    "Necklet Orange.png",
    "Necklet White.png",
    "Necklet Yellow.png",
    "None.png",
    "Peebles Dark.png",
    "Peebles Gems.png",
    "Peebles Jade.png",
    "Peebles Light.png",
    "Peebles Red.png",
    "Peebles Sand.png",
    "Tight Black.png",
    "Tight Glowing  Opal.png",
    "Tight Gold.png",
    "Tight Lime Stone.png",
    "Tight Rubi.png",
    "Tight Turquoise.png",
    "Wood Opal.png",
    "Wood.png"
  ],
  "Eyes": [
    "Angry Blue Paint Yellow Side.png",
    "Angry Green Front.png",
    "Angry Pink Side.png",
    "Angry Red Paint Turquoise Side.png",
    "Angry Red Side.png",
    "Angry Turquoise Side.png",
    "Attention Blue Paint Blue Front.png",
    "Attention Blue Paint Brown Front.png",
    "Attention Blue Paint Yellow Front.png",
    "Attention Wine Paint Pink Front.png",
    "Cat Blue Side.png",
    "Cat Gray Side.png",
    "Cat Jade Side.png",
    "Cat Red Front.png",
    "Cat Strawberry Side.png",
    "Cat Trippy Side.png",
    "Cat Turquoise Front.png",
    "Cat Yellow Front.png",
    "Cat Yellow Side.png",
    "Fury Blue Front.png",
    "Fury Blue Painted Blue Side.png",
    "Fury Blue Painted Brown Front.png",
    "Fury Blue Painted Green Side.png",
    "Fury Blue Painted Red Side.png",
    "Fury Blue Painted Yellow Side.png",
    "Fury Blue Side.png",
    "Fury Green Front.png",
    "Fury Green Painted Blue Side.png",
    "Fury Pink Painted brown Side.png",
    "Fury Purple Painted Front.png",
    "Fury Red Front.png",
    "Fury Red Side.png",
    "Fury Side Green.png",
    "Fury Turquoise Side.png",
    "Fury Wine Painted Orange Side.png",
    "Fury Yellow Side.png",
    "Happy BGreen Double Paint.png",
    "Happy Blue Paint.png",
    "Happy Double Pink Paint.png",
    "Happy Red Paint.png",
    "Happy.png",
    "Midst Blue Side.png",
    "Midst Brown Side.png",
    "Midst Green Paint Green Front.png",
    "Midst Green Side.png",
    "Midst Pink Paint Green Side.png",
    "Midst Red Paint Blue Side.png",
    "Midst Red Paint Brown Front.png",
    "Midst Red Paint Green Side.png",
    "Midst Red Paint Yellow Side.png",
    "Midst Red Side.png",
    "Midst Turquoise Side.png",
    "Midst Violet Paint Front.png",
    "Rounded Blue Front.png",
    "Rounded Gray Paint Front.png",
    "Rounded Pink Green Paint Front.png",
    "Rounded Red Blue Paint Front.png",
    "Rounded Red Front.png",
    "Rounded Sand Jade Paint Front.png",
    "Rounded Turquoise Blue Paint Front.png",
    "Rounded Turquoise Front.png",
    "Rounded Violet Paint  Front.png",
    "Shy Blue Purple Paint Side.png",
    "Shy Blue Red Paint Side.png",
    "Shy Brown Side.png",
    "Shy Dark Blue Paint Side.png",
    "Shy Gold Paint Side.png",
    "Shy Green Side.png",
    "Shy Light Blue Side.png",
    "Shy Pink Paint Side.png",
    "Shy Red Paint Side.png",
    "Shy Turquoise Red Paint Side.png",
    "Shy Yellow Side.png",
    "Suprised Blue Paint Yellow Side.png",
    "Suprised Purple Side.png",
    "Suprised Red Paint Blue Side.png",
    "Suprised Red Side.png",
    "Suprised Turquoise Side.png",
    "Triangle Blue Paint Red Front.png",
    "Triangle Blue Paint Turquoise Front.png",
    "Triangle Blue Paint Yellow Side.png",
    "Triangle Gold Paint Purple Front.png",
    "Triangle Purple Paint Green Side.png",
    "Triangle Red Paint Blue Side.png",
    "Triangle Red Paint Yellow Side.png",
    "serious yellow side.png",
    "Angry Blue Paint Turquoise Side.png",
    "Cat Trippy Front.png",
    "Shy Blue Side.png",
    "Triangle Green Paint Green Front.png"
  ],
  "Mouth": [
    "Angry Black.png",
    "Angry Green.png",
    "Angry Pink.png",
    "Angry Red.png",
    "Angry Turquoise.png",
    "Angry.png",
    "Cunning.png",
    "Happy Vampire Blue.png",
    "Happy Vampire Gray.png",
    "Happy Vampire Green.png",
    "Happy Vampire Naked.png",
    "Happy Vampire Pink.png",
    "Happy Vampire Red.png",
    "Happy Vampire Yellow.png",
    "Laughing Black.png",
    "Laughing Real Blue.png",
    "Laughing Real Green.png",
    "Laughing Real Pink.png",
    "Laughing.png",
    "Lined Mouth.png",
    "Neko Black.png",
    "Neko Green.png",
    "Neko Pink.png",
    "Neko.png",
    "Open Blue.png",
    "Open Real Pink.png",
    "Open Real Purple.png",
    "Open Red.png",
    "Open.png",
    "Ordinary Black.png",
    "Ordinary Blue.png",
    "Ordinary Mint.png",
    "Ordinary Red.png",
    "Ordinary.png",
    "Regular.png",
    "Rogue.png",
    "Serious Black.png",
    "Serious Red.png",
    "Serious.png",
    "Small Blue.png",
    "Small Red.png",
    "Small.png",
    "Smile Black.png",
    "Smile Blue.png",
    "Smile Red.png",
    "Smile.png",
    "Vampire Black.png",
    "Vampire Blue.png",
    "Vampire Naked.png",
    "Vampire Red.png"
  ],
  "Hair": [
    "Alan Black.png",
    "Alan Blonde.png",
    "Alan Blue.png",
    "Alan Brown.png",
    "Alan Pink.png",
    "Alan Red.png",
    "Alan Silver.png",
    "Blowout Blonde.png",
    "Blowout Blue.png",
    "Blowout Dark.png",
    "Blowout Green.png",
    "Blowout Red.png",
    "Crest Black.png",
    "Crest Blonde.png",
    "Crest Blue.png",
    "Crest Brown.png",
    "Crest Green.png",
    "Crest Pink.png",
    "Crest Red.png",
    "Crest Silver.png",
    "Messy Black.png",
    "Messy Blonde.png",
    "Messy Blue.png",
    "Messy Brown.png",
    "Messy Pink.png",
    "Messy Silver.png",
    "Ponytail Black.png",
    "Ponytail Blonde.png",
    "Ponytail Blue.png",
    "Ponytail Brown.png",
    "Ponytail Pink.png",
    "Ponytail Red.png",
    "Ponytail Silver.png",
    "Samurai Black.png",
    "Samurai Blonde.png",
    "Samurai Blue.png",
    "Samurai Brown.png",
    "Samurai Green.png",
    "Samurai Pink.png",
    "Samurai Red.png",
    "Samurai Silver.png",
    "Short Black.png",
    "Short Blonde.png",
    "Short Brown.png",
    "Short Pink.png",
    "Short Red.png",
    "Short Silver.png",
    "Blowout Dark Blue.png"
  ],
  "Earring": [
    "Big Blue Feather.png",
    "Big Brown Feather.png",
    "Big Cobalt Feather.png",
    "Canine Ivory.png",
    "Canine Jade.png",
    "Canine Rubi.png",
    "Climber.png",
    "Double Ring.png",
    "placeholder",
    "Duck Fluorite.png",
    "placeholder",
    "Duck Gold.png",
    "placeholder",
    "Duck Rubi.png",
    "Gold Ring.png",
    "Gold and Turquoise Disc.png",
    "Jaguar.png",
    "None.png",
    "Single Old Gold Ring.png",
    "Single Ring.png",
    "Stones Jade.png",
    "Stones Obsidian.png",
    "Stones River.png",
    "Tip Jade.png",
    "Tip.png",
    "Canine Obsidian.png",
    "Duck Ivory.png",
    "Duck Obsidian.png",
    "Set Golden.png",
    "Set Obsidian.png",
    "Stones Rubi.png"
  ],
  "Mask": [
    "Bear Blue.png",
    "Bear Brown.png",
    "Bear Fury.png",
    "Bear White.png",
    "Birdie Green.png",
    "Birdie Red.png",
    "Birdie White.png",
    "Birdy Blue.png",
    "Dog Black.png",
    "Dog Brown.png",
    "Dog Green.png",
    "Dog Light Blue.png",
    "Dog Pink.png",
    "Dog White.png",
    "Eagle Blue Gold.png",
    "Eagle Blue Green.png",
    "Eagle Blue.png",
    "Eagle Dark Orange.png",
    "Eagle Lime.png",
    "Eagle Matte Blue.png",
    "Eagle Orange.png",
    "Eagle Pink.png",
    "Eagle Red.png",
    "Eagle Violet.png",
    "Eagle white.png",
    "Explorer Blue.png",
    "Explorer Purple.png",
    "Explorer Red.png",
    "Explorer Yellow.png",
    "Gator Blue.png",
    "Gator Dark Green.png",
    "Gator Gold.png",
    "Gator Green.png",
    "Gator Violet.png",
    "Gator White.png",
    "Hare Blue.png",
    "Hare Gold.png",
    "Hare Green.png",
    "Hare Red.png",
    "Hare White.png",
    "Jaguar Blue.png",
    "Jaguar Brown Blue.png",
    "Jaguar Dark Blue.png",
    "Jaguar Green.png",
    "Jaguar Red Green.png",
    "Jaguar Violet.png",
    "Jaguar White Blue.png",
    "Jaguar White Red.png",
    "Jaguar Yellow Blue.png",
    "Jaguar Yellow Green.png",
    "Jaguar Yellow Red.png",
    "King Blue.png",
    "King Crown Red.png",
    "King Red.png",
    "Owl Blue.png",
    "placeholder",
    "Owl Bright.png",
    "Owl Brown.png",
    "Owl Gray.png",
    "Owl Green Red.png",
    "Owl Green.png",
    "Owl Pink.png",
    "Owl Red.png",
    "Owl Turquoise.png",
    "Owl White Blue.png",
    "Owl White.png",
    "Owl test.png",
    "Parrot Blue.png",
    "Parrot Green.png",
    "Parrot Orange.png",
    "Parrot Pink.png",
    "Parrot Red.png",
    "Parrot Turquoise.png",
    "Priest Green.png",
    "Priest Grey.png",
    "Priest White.png",
    "Rabbit Brown Blue.png",
    "Rabbit Brown Brown.png",
    "Rabbit Brown Green.png",
    "Rabbit Dark Blue.png",
    "Rabbit Dark Green Red Eyes.png",
    "Rabbit Dark Red.png",
    "Rabbit Gray.png",
    "Rabbit Green.png",
    "Rabbit Red Blue.png",
    "Rabbit Violet.png",
    "Rabbit White Blue.png",
    "Serpent Blue.png",
    "Serpent Dark Blue.png",
    "Serpent Jade.png",
    "Serpent Light Green.png",
    "Serpent Purple.png",
    "Serpent Red.png",
    "Serpent Turquoise.png",
    "Serpent White.png",
    "Warrior Jade.png",
    "king crown blue.png",
    "Diadem Rainbow.png",
    "Owl Blue Orange.png",
    "Rare Mosaic Gold.png"
  ]
}
export const maleNoMaskedOG = {
  "Background": [
    "Aqua.png",
    "Aristocracy.png",
    "Bamboo Gradient.png",
    "Bamboo Purple.png",
    "Bamboo Red.png",
    "Bamboo Tropic.png",
    "Black Hole.png",
    "Bubbles Blue.png",
    "Bubbles Pink.png",
    "Calendar Lilac.png",
    "Calendar Ruby.png",
    "Calendar Violet.png",
    "Celeste.png",
    "Double Moons Cloud.png",
    "Double Moons Dark Blue.png",
    "Double Moons Fire.png",
    "Double Moons Mint.png",
    "Double Moons Yellow.png",
    "Fire.png",
    "Flowers Blue.png",
    "Flowers Grey.png",
    "Flowers Middle Green.png",
    "Forest.png",
    "Gators dark.png",
    "Gradient Blue.png",
    "Gradient Gold.png",
    "Gradient Green.png",
    "Gradient Pink.png",
    "Gradient Purple.png",
    "Gradient Red.png",
    "J_Toons.png",
    "Lavender.png",
    "Leaf Glow.png",
    "Leaf Violet.png",
    "Lilac.png",
    "Lines.png",
    "Marble Blue.png",
    "Marble Malva.png",
    "Marble Pink.png",
    "Mint.png",
    "Mosaic Lilac.png",
    "Pastel Cloud.png",
    "Pink Vector.png",
    "Pyramid Azure.png",
    "Pyramid Dark Blue.png",
    "Pyramid Dark Green.png",
    "Pyramid Dark Pink.png",
    "Pyramid Sunrise.png",
    "Real Pastel.png",
    "Red Vector.png",
    "Ring Glow Pink.png",
    "Ring Mint.png",
    "Sand.png",
    "Skulls Contrast.png",
    "Skulls Dark.png",
    "Skulls Neon.png",
    "Skulls Orange.png",
    "Solid Green.png",
    "Solid Wine.png",
    "Stone Blue.png",
    "Stone Gold.png",
    "Stone Jade.png",
    "Stone Orange.png",
    "Stone Purple.png",
    "Stone Sand.png",
    "Stone Turqoise.png",
    "Sun All Red.png",
    "Sun Gold.png",
    "Sun Yellow.png",
    "Yellow.png",
    "Bubbles Green.png",
    "Double Moons Dark Orange.png",
    "Skulls Black.png",
    "Skulls Red.png",
    "Sun Orange.png"
  ],
  "Body": [
    "Blue.png",
    "Chestnut.png",
    "DoD OG.png",
    "Green.png",
    "Honey.png",
    "Porcelain.png",
    "Red.png",
    "Siena.png",
    "Warm Ivory.png"
  ],
  "Dress": [
    "Body Paint Blue.png",
    "Body Paint Dark Green.png",
    "Body Paint Dark.png",
    "Body Paint Fire.png",
    "Body Paint Jade.png",
    "Body Paint Light Green.png",
    "Body Paint Purple.png",
    "Body Paint Red.png",
    "Pattern Tattoo Black.png",
    "Pattern Tattoo Blue.png",
    "Pattern Tattoo DoD.png",
    "Pattern Tattoo Full White.png",
    "Pattern Tattoo Green.png",
    "Pattern Tattoo Red.png",
    "Pattern Tattoo Turquoise.png",
    "Quechquémitl Black.png",
    "Quechquémitl Gold.png",
    "Quechquémitl Gray.png",
    "Quechquémitl Green.png",
    "Quechquémitl Lime.png",
    "Quechquémitl Purple.png",
    "Quechquémitl Turquoise.png",
    "Quechquémitl White.png",
    "Rainbow Body Paint.png",
    "Stripes Tattoo Blue.png",
    "Stripes Tattoo Brown.png",
    "Stripes Tattoo Dark Green.png",
    "Stripes Tattoo Gray.png",
    "Stripes Tattoo Light Blue.png",
    "Stripes Tattoo Light Green.png",
    "Stripes Tattoo Red.png",
    "Stripes Tattoo White.png",
    "Stripes Tattoo Yellow.png",
    "Sun Tattoo Black Tee.png",
    "Sun Tattoo Blue Tee.png",
    "Sun Tattoo Coral.png",
    "Sun Tattoo Green Tee.png",
    "Sun Tattoo Mint Tee.png",
    "Sun Tattoo Orange Tee.png",
    "Sun Tattoo Red Tee.png",
    "Sun Tee Grey.png",
    "Sun Tee.png",
    "Tee Green.png",
    "Tee Turquoise.png",
    "Tee.png",
    "Triangles Tattoo Blue.png",
    "Triangles Tattoo Bright Red.png",
    "Triangles Tattoo Dark Green.png",
    "Triangles Tattoo Green.png",
    "Triangles Tattoo Orange.png",
    "Triangles Tattoo Red.png",
    "Triangles Tattoo Sky.png",
    "Triangles Tattoo White.png",
    "Triangles Tattoo Yellow.png",
    "Tribal Blue.png",
    "Tribal Full Body Black.png",
    "Tribal Full Body Blue.png",
    "Tribal Full Body Dark Blue.png",
    "Tribal Full Body Gold.png",
    "Tribal Full Body Red.png",
    "Tribal Full Body White.png",
    "Tribal Full Body.png",
    "Tribal Red.png",
    "Tribal Tee Black.png",
    "Tribal Tee Blue.png",
    "Tribal Tee Gray.png",
    "Tribal Tee Green.png",
    "Tribal Tee Purple.png",
    "Tribal Tee Red.png",
    "Tribal Tee Sand.png",
    "Tribal Tee White.png",
    "Tribal Tee Yellow.png"
  ],
  "Face Paint": [
    "Armour Copper.png",
    "Armour Gold.png",
    "Armour Jade.png",
    "Armour Obsidian.png",
    "Blaze Blue Pastel.png",
    "Blaze Blue.png",
    "Blaze Brown.png",
    "Blaze Dark Blue.png",
    "Blaze Green Yellow.png",
    "Blaze Green.png",
    "Blaze Grey and Gold.png",
    "Blaze Red.png",
    "Blaze Violet Pastel.png",
    "Blaze Yellow.png",
    "Flare Black.png",
    "Flare Blue.png",
    "Flare Dark Blue.png",
    "Flare Dark Green.png",
    "Flare Dark Turquoise.png",
    "Flare Green.png",
    "Flare Grey.png",
    "Flare Pink.png",
    "Flare Red.png",
    "Flare White Blue.png",
    "Flare White Orange.png",
    "Flare Yellow.png",
    "Fold Black.png",
    "Fold Blue.png",
    "Fold Gray.png",
    "Fold Green.png",
    "Fold Light Blue.png",
    "Fold Light Red.png",
    "Fold Orange.png",
    "Fold Red.png",
    "Fold Turquoise.png",
    "Fold Yellow.png",
    "Full Face Black.png",
    "Full Face Blue.png",
    "Full Face Gold.png",
    "Full Face Light Red.png",
    "Full Face Orange.png",
    "Full Face Red.png",
    "Full Face White.png",
    "Half Face Simple Black.png",
    "Half Face Simple Blue Violet.png",
    "Half Face Simple Blue.png",
    "Half Face Simple Green.png",
    "Half Face Simple Light Blue.png",
    "Half Face Simple Orange.png",
    "Half Face Simple Red.png",
    "Half Face Simple Turquoise.png",
    "Half Face Simple Yellow.png",
    "Mark Black.png",
    "Mark Blue.png",
    "Mark Brown.png",
    "Mark Dark Blue.png",
    "Mark Fire.png",
    "Mark Green.png",
    "Mark Light Blue.png",
    "Mark Light Yellow.png",
    "Mark Orange.png",
    "Mark Red.png",
    "None.png",
    "Zigzag Black.png",
    "Zigzag Blue.png",
    "Zigzag Brown.png",
    "Zigzag Green.png",
    "Zigzag Red.png",
    "Zigzag Yellow.png",
    "Flare Gold.png",
    "Full Face Green.png",
    "Mark Yellow.png"
  ],
  "Necklace": [
    "Armour Copper.png",
    "Armour Gold.png",
    "Armour Jade.png",
    "Armour Obsidian.png",
    "Board Side Ivory.png",
    "Boards Gold.png",
    "Boards Ivory.png",
    "Boards Jade.png",
    "Boards Obsidian.png",
    "placeholder",
    "Boards Rubi.png",
    "Boards Side Gold.png",
    "Boards Turquoise.png",
    "Bulb Gold.png",
    "Bulb Jade.png",
    "Bulb Turquoisee.png",
    "Demon Tattoo Black.png",
    "Demon Tattoo Red.png",
    "Demon Tattoo Turquoise.png",
    "Demon Tattoo White.png",
    "King Lapis Lazuli.png",
    "King Rubii.png",
    "King.png",
    "Leather Mosaic Blue.png",
    "Leather Mosaic Grey.png",
    "Necklet Blue.png",
    "Necklet Orange.png",
    "Necklet White.png",
    "Necklet Yellow.png",
    "None.png",
    "Peebles Dark.png",
    "Peebles Gems.png",
    "Peebles Jade.png",
    "Peebles Light.png",
    "Peebles Red.png",
    "Peebles Sand.png",
    "Tight Black.png",
    "Tight Glowing  Opal.png",
    "Tight Gold.png",
    "Tight Lime Stone.png",
    "Tight Rubi.png",
    "Tight Turquoise.png",
    "Wood Opal.png",
    "Wood.png"
  ],
  "Eyes": [
    "Angry Blue Paint Yellow Side.png",
    "Angry Green Front.png",
    "Angry Pink Side.png",
    "Angry Red Paint Turquoise Side.png",
    "Angry Red Side.png",
    "Angry Turquoise Side.png",
    "Attention Blue Paint Blue Front.png",
    "Attention Blue Paint Brown Front.png",
    "Attention Blue Paint Yellow Front.png",
    "Attention Wine Paint Pink Front.png",
    "Cat Blue Side.png",
    "Cat Gray Side.png",
    "Cat Jade Side.png",
    "Cat Red Front.png",
    "Cat Strawberry Side.png",
    "Cat Trippy Side.png",
    "Cat Turquoise Front.png",
    "Cat Yellow Front.png",
    "Cat Yellow Side.png",
    "Fury Blue Front.png",
    "Fury Blue Painted Blue Side.png",
    "Fury Blue Painted Brown Front.png",
    "Fury Blue Painted Green Side.png",
    "Fury Blue Painted Red Side.png",
    "Fury Blue Painted Yellow Side.png",
    "Fury Blue Side.png",
    "Fury Green Front.png",
    "Fury Green Painted Blue Side.png",
    "Fury Pink Painted brown Side.png",
    "Fury Purple Painted Front.png",
    "Fury Red Front.png",
    "Fury Red Side.png",
    "Fury Side Green.png",
    "Fury Turquoise Side.png",
    "Fury Wine Painted Orange Side.png",
    "Fury Yellow Side.png",
    "Happy BGreen Double Paint.png",
    "Happy Blue Paint.png",
    "Happy Double Pink Paint.png",
    "Happy Red Paint.png",
    "Happy.png",
    "Midst Blue Side.png",
    "Midst Brown Side.png",
    "Midst Green Paint Green Front.png",
    "Midst Green Side.png",
    "Midst Pink Paint Green Side.png",
    "Midst Red Paint Blue Side.png",
    "Midst Red Paint Brown Front.png",
    "Midst Red Paint Green Side.png",
    "Midst Red Paint Yellow Side.png",
    "Midst Red Side.png",
    "Midst Turquoise Side.png",
    "Midst Violet Paint Front.png",
    "Rounded Blue Front.png",
    "Rounded Gray Paint Front.png",
    "Rounded Pink Green Paint Front.png",
    "Rounded Red Blue Paint Front.png",
    "Rounded Red Front.png",
    "Rounded Sand Jade Paint Front.png",
    "Rounded Turquoise Blue Paint Front.png",
    "Rounded Turquoise Front.png",
    "Rounded Violet Paint  Front.png",
    "Shy Blue Purple Paint Side.png",
    "Shy Blue Red Paint Side.png",
    "Shy Brown Side.png",
    "Shy Dark Blue Paint Side.png",
    "Shy Gold Paint Side.png",
    "Shy Green Side.png",
    "Shy Light Blue Side.png",
    "Shy Pink Paint Side.png",
    "Shy Red Paint Side.png",
    "Shy Turquoise Red Paint Side.png",
    "Shy Yellow Side.png",
    "Suprised Blue Paint Yellow Side.png",
    "Suprised Purple Side.png",
    "Suprised Red Paint Blue Side.png",
    "Suprised Red Side.png",
    "Suprised Turquoise Side.png",
    "Triangle Blue Paint Red Front.png",
    "Triangle Blue Paint Turquoise Front.png",
    "Triangle Blue Paint Yellow Side.png",
    "Triangle Gold Paint Purple Front.png",
    "Triangle Purple Paint Green Side.png",
    "Triangle Red Paint Blue Side.png",
    "Triangle Red Paint Yellow Side.png",
    "serious yellow side.png",
    "Angry Blue Paint Turquoise Side.png",
    "Cat Trippy Front.png",
    "Shy Blue Side.png",
    "Triangle Green Paint Green Front.png"
  ],
  "Mouth": [
    "Angry Black.png",
    "Angry Green.png",
    "Angry Pink.png",
    "Angry Red.png",
    "Angry Turquoise.png",
    "Angry.png",
    "Cunning.png",
    "Happy Vampire Blue.png",
    "Happy Vampire Gray.png",
    "Happy Vampire Green.png",
    "Happy Vampire Naked.png",
    "Happy Vampire Pink.png",
    "Happy Vampire Red.png",
    "Happy Vampire Yellow.png",
    "Laughing Black.png",
    "Laughing Real Blue.png",
    "Laughing Real Green.png",
    "Laughing Real Pink.png",
    "Laughing.png",
    "Lined Mouth.png",
    "Neko Black.png",
    "Neko Green.png",
    "Neko Pink.png",
    "Neko.png",
    "Open Blue.png",
    "Open Real Pink.png",
    "Open Real Purple.png",
    "Open Red.png",
    "Open.png",
    "Ordinary Black.png",
    "Ordinary Blue.png",
    "Ordinary Mint.png",
    "Ordinary Red.png",
    "Ordinary.png",
    "Regular.png",
    "Rogue.png",
    "Serious Black.png",
    "Serious Red.png",
    "Serious.png",
    "Small Blue.png",
    "Small Red.png",
    "Small.png",
    "Smile Black.png",
    "Smile Blue.png",
    "Smile Red.png",
    "Smile.png",
    "Vampire Black.png",
    "Vampire Blue.png",
    "Vampire Naked.png",
    "Vampire Red.png"
  ],
  "Hair": [
    "Alan Black.png",
    "Alan Blonde.png",
    "Alan Blue.png",
    "Alan Brown.png",
    "Alan Pink.png",
    "Alan Red.png",
    "Alan Silver.png",
    "Blowout Black.png",
    "Blowout Blonde.png",
    "Blowout Blue.png",
    "Blowout Fire.png",
    "Blowout Green.png",
    "Blowout Red.png",
    "Blowout Silver.png",
    "Crest Black.png",
    "Crest Blonde.png",
    "Crest Blue.png",
    "Crest Brown.png",
    "Crest Green.png",
    "Crest Pink.png",
    "Crest Red.png",
    "Crest Silver.png",
    "Faux Hawk Black.png",
    "Faux Hawk Blonde.png",
    "Faux Hawk Blue.png",
    "Faux Hawk Green.png",
    "Faux Hawk Pink.png",
    "Faux Hawk Red.png",
    "Faux Hawk Silver.png",
    "Faux Hawk Violet.png",
    "Liberty Spikes Blue.png",
    "Liberty Spikes Green.png",
    "Liberty Spikes Pink.png",
    "Liberty Spikes Red.png",
    "Liberty Spikes White.png",
    "Liberty Spikes Yellow.png",
    "Long Black Shaved Side.png",
    "Long Blonde Shaved Side.png",
    "Long Blue Shaved Side.png",
    "Long Brown Shaved Side.png",
    "Long Green Shaved Side.png",
    "Long Pink Shaved Side.png",
    "Long Red Shaved Side.png",
    "Long Silver Shaved Side.png",
    "Messy Black.png",
    "Messy Blonde.png",
    "Messy Blue.png",
    "Messy Brown.png",
    "Messy Pink.png",
    "Messy Silver.png",
    "Ponytail Black.png",
    "Ponytail Blonde.png",
    "Ponytail Blue.png",
    "Ponytail Brown.png",
    "Ponytail Pink.png",
    "Ponytail Red.png",
    "Ponytail Silver.png",
    "Ridge Black.png",
    "Ridge Blonde.png",
    "Ridge Blue.png",
    "Ridge Brown.png",
    "Ridge Green.png",
    "Ridge Pink.png",
    "Ridge Silver.png",
    "Ridge fire.png",
    "Samurai Black.png",
    "Samurai Blonde.png",
    "Samurai Blue.png",
    "Samurai Brown.png",
    "Samurai Green.png",
    "Samurai Pink.png",
    "Samurai Red.png",
    "Samurai Silver.png",
    "Short Black.png",
    "Short Blonde.png",
    "Short Brown.png",
    "Short Pink.png",
    "Short Red.png",
    "Short Silver.png",
    "Blowout Pink.png",
    "Blowout Purple.png"
  ],
  "Earring": [
    "Big Blue Feather.png",
    "Big Brown Feather.png",
    "Big Cobalt Feather.png",
    "Canine Ivory.png",
    "Canine Jade.png",
    "Canine Rubi.png",
    "Climber.png",
    "Double Ring.png",
    "Gold Ring.png",
    "Gold and Turquoise Disc.png",
    "Jaguar.png",
    "None.png",
    "Single Old Gold Ring.png",
    "Single Ring.png",
    "Stones Jade.png",
    "Stones Obsidian.png",
    "Stones River.png",
    "Tip Jade.png",
    "Tip.png",
    "Canine Obsidian.png",
    "Duck Ivory.png",
    "Duck Obsidian.png",
    "Set Golden.png",
    "Set Obsidian.png",
    "Stones Rubi.png"
  ],
  "Mask": [
    "None.png"
  ]
}
export const MaleOpenMaskedOG = {
  "Background": [
    "Aqua.png",
    "Aristocracy.png",
    "Bamboo Gradient.png",
    "Bamboo Purple.png",
    "Bamboo Red.png",
    "Bamboo Tropic.png",
    "Black Hole.png",
    "Bubbles Blue.png",
    "Bubbles Pink.png",
    "Calendar Lilac.png",
    "Calendar Ruby.png",
    "Calendar Violet.png",
    "Celeste.png",
    "Double Moons Cloud.png",
    "Double Moons Dark Blue.png",
    "Double Moons Fire.png",
    "Double Moons Mint.png",
    "Double Moons Yellow.png",
    "Fire.png",
    "Flowers Blue.png",
    "Flowers Grey.png",
    "Flowers Middle Green.png",
    "Forest.png",
    "Gators dark.png",
    "Gradient Blue.png",
    "Gradient Gold.png",
    "Gradient Green.png",
    "Gradient Pink.png",
    "Gradient Purple.png",
    "Gradient Red.png",
    "J_Toons.png",
    "Lavender.png",
    "Leaf Glow.png",
    "Leaf Violet.png",
    "Lilac.png",
    "Lines.png",
    "Marble Blue.png",
    "Marble Malva.png",
    "Marble Pink.png",
    "Mint.png",
    "Mosaic Lilac.png",
    "Pastel Cloud.png",
    "Pink Vector.png",
    "Pyramid Azure.png",
    "Pyramid Dark Blue.png",
    "Pyramid Dark Green.png",
    "Pyramid Dark Pink.png",
    "Pyramid Sunrise.png",
    "Real Pastel.png",
    "Red Vector.png",
    "Ring Glow Pink.png",
    "Ring Mint.png",
    "Sand.png",
    "Skulls Contrast.png",
    "Skulls Dark.png",
    "Skulls Neon.png",
    "Skulls Orange.png",
    "Solid Green.png",
    "Solid Wine.png",
    "Stone Blue.png",
    "Stone Gold.png",
    "Stone Jade.png",
    "Stone Orange.png",
    "Stone Purple.png",
    "Stone Sand.png",
    "Stone Turqoise.png",
    "Sun All Red.png",
    "Sun Gold.png",
    "Sun Yellow.png",
    "Yellow.png"
  ],
  "Body": [
    "Blue.png",
    "Chestnut.png",
    "DoD OG.png",
    "Green.png",
    "Honey.png",
    "Porcelain.png",
    "Red.png",
    "Siena.png",
    "Warm Ivory.png"
  ],
  "Dress": [
    "Body Paint Blue.png",
    "Body Paint Dark Green.png",
    "Body Paint Dark.png",
    "Body Paint Fire.png",
    "Body Paint Jade.png",
    "Body Paint Light Green.png",
    "Body Paint Purple.png",
    "Body Paint Red.png",
    "Pattern Tattoo Black.png",
    "Pattern Tattoo Blue.png",
    "Pattern Tattoo DoD.png",
    "Pattern Tattoo Full White.png",
    "Pattern Tattoo Green.png",
    "Pattern Tattoo Red.png",
    "Pattern Tattoo Turquoise.png",
    "Quechquémitl Black.png",
    "Quechquémitl Gold.png",
    "Quechquémitl Gray.png",
    "Quechquémitl Green.png",
    "Quechquémitl Lime.png",
    "Quechquémitl Purple.png",
    "Quechquémitl Turquoise.png",
    "Quechquémitl White.png",
    "Rainbow Body Paint.png",
    "Stripes Tattoo Blue.png",
    "Stripes Tattoo Brown.png",
    "Stripes Tattoo Dark Green.png",
    "Stripes Tattoo Gray.png",
    "Stripes Tattoo Light Blue.png",
    "Stripes Tattoo Light Green.png",
    "Stripes Tattoo Red.png",
    "Stripes Tattoo White.png",
    "Stripes Tattoo Yellow.png",
    "Sun Tattoo Black Tee.png",
    "Sun Tattoo Blue Tee.png",
    "Sun Tattoo Coral.png",
    "Sun Tattoo Green Tee.png",
    "Sun Tattoo Mint Tee.png",
    "Sun Tattoo Orange Tee.png",
    "Sun Tattoo Red Tee.png",
    "Sun Tee Grey.png",
    "Sun Tee.png",
    "Tee Green.png",
    "Tee Turquoise.png",
    "Tee.png",
    "Triangles Tattoo Blue.png",
    "Triangles Tattoo Bright Red.png",
    "Triangles Tattoo Dark Green.png",
    "Triangles Tattoo Green.png",
    "Triangles Tattoo Orange.png",
    "Triangles Tattoo Red.png",
    "Triangles Tattoo Sky.png",
    "Triangles Tattoo White.png",
    "Triangles Tattoo Yellow.png",
    "Tribal Blue.png",
    "Tribal Full Body Black.png",
    "Tribal Full Body Blue.png",
    "Tribal Full Body Dark Blue.png",
    "Tribal Full Body Gold.png",
    "Tribal Full Body Red.png",
    "Tribal Full Body White.png",
    "Tribal Full Body.png",
    "Tribal Red.png",
    "Tribal Tee Black.png",
    "Tribal Tee Blue.png",
    "Tribal Tee Gray.png",
    "Tribal Tee Green.png",
    "Tribal Tee Purple.png",
    "Tribal Tee Red.png",
    "Tribal Tee Sand.png",
    "Tribal Tee White.png",
    "Tribal Tee Yellow.png"
  ],
  "Face Paint": [
    "Armour Copper.png",
    "Armour Gold.png",
    "Armour Jade.png",
    "Armour Obsidian.png",
    "Blaze Blue Pastel.png",
    "Blaze Blue.png",
    "Blaze Brown.png",
    "Blaze Dark Blue.png",
    "Blaze Green Yellow.png",
    "Blaze Green.png",
    "Blaze Grey and Gold.png",
    "Blaze Red.png",
    "Blaze Violet Pastel.png",
    "Blaze Yellow.png",
    "Flare Black.png",
    "Flare Blue.png",
    "Flare Dark Blue.png",
    "Flare Dark Green.png",
    "Flare Dark Turquoise.png",
    "Flare Green.png",
    "Flare Grey.png",
    "Flare Pink.png",
    "Flare Red.png",
    "Flare White Blue.png",
    "Flare White Orange.png",
    "Flare Yellow.png",
    "Fold Black.png",
    "Fold Blue.png",
    "Fold Gray.png",
    "Fold Green.png",
    "Fold Light Blue.png",
    "Fold Light Red.png",
    "Fold Orange.png",
    "Fold Red.png",
    "Fold Turquoise.png",
    "Fold Yellow.png",
    "Full Face Black.png",
    "Full Face Blue.png",
    "Full Face Gold.png",
    "Full Face Light Red.png",
    "Full Face Orange.png",
    "Full Face Red.png",
    "Full Face White.png",
    "Half Face Simple Black.png",
    "Half Face Simple Blue Violet.png",
    "Half Face Simple Blue.png",
    "Half Face Simple Green.png",
    "Half Face Simple Light Blue.png",
    "Half Face Simple Orange.png",
    "Half Face Simple Red.png",
    "Half Face Simple Turquoise.png",
    "Half Face Simple Yellow.png",
    "Mark Black.png",
    "Mark Blue.png",
    "Mark Brown.png",
    "Mark Dark Blue.png",
    "Mark Fire.png",
    "Mark Green.png",
    "Mark Light Blue.png",
    "Mark Light Yellow.png",
    "Mark Orange.png",
    "Mark Red.png",
    "None.png",
    "Zigzag Black.png",
    "Zigzag Blue.png",
    "Zigzag Brown.png",
    "Zigzag Green.png",
    "Zigzag Red.png",
    "Zigzag Yellow.png"
  ],
  "Necklace": [
    "Armour Copper.png",
    "Armour Gold.png",
    "Armour Jade.png",
    "Armour Obsidian.png",
    "Board Side Ivory.png",
    "Boards Blue.png",
    "Boards Gold.png",
    "Boards Ivory.png",
    "Boards Jade.png",
    "Boards Obsidian.png",
    "placeholder",
    "Boards Rubi.png",
    "Boards Side Gold.png",
    "Boards Turquoise.png",
    "Bulb Gold.png",
    "Bulb Jade.png",
    "Bulb Turquoisee.png",
    "Demon Tattoo Black.png",
    "Demon Tattoo Red.png",
    "Demon Tattoo Turquoise.png",
    "Demon Tattoo White.png",
    "King Lapis Lazuli.png",
    "King Rubii.png",
    "King.png",
    "Leather Mosaic Blue.png",
    "Leather Mosaic Grey.png",
    "Necklet Blue.png",
    "Necklet Orange.png",
    "Necklet White.png",
    "Necklet Yellow.png",
    "None.png",
    "Peebles Dark.png",
    "Peebles Gems.png",
    "Peebles Jade.png",
    "Peebles Light.png",
    "Peebles Red.png",
    "Peebles Sand.png",
    "Tight Black.png",
    "Tight Glowing Opal.png",
    "Tight Gold.png",
    "Tight Lime Stone.png",
    "Tight Rubi.png",
    "Tight Turquoise.png",
    "Wood Opal.png",
    "Wood.png"
  ],
  "Eyes": [
    "Angry Blue Paint Yellow Side.png",
    "Angry Green Front.png",
    "Angry Pink Side.png",
    "Angry Red Paint Turquoise Side.png",
    "Angry Red Side.png",
    "Angry Turquoise Side.png",
    "Attention Blue Paint Blue Front.png",
    "Attention Blue Paint Brown Front.png",
    "Attention Blue Paint Yellow Front.png",
    "Attention Wine Paint Pink Front.png",
    "Cat Blue Side.png",
    "Cat Gray Side.png",
    "Cat Jade Side.png",
    "Cat Red Front.png",
    "Cat Strawberry Side.png",
    "Cat Trippy Side.png",
    "Cat Turquoise Front.png",
    "Cat Yellow Front.png",
    "Cat Yellow Side.png",
    "Fury Blue Front.png",
    "Fury Blue Painted Blue Side.png",
    "Fury Blue Painted Brown Front.png",
    "Fury Blue Painted Green Side.png",
    "Fury Blue Painted Red Side.png",
    "Fury Blue Painted Yellow Side.png",
    "Fury Blue Side.png",
    "Fury Green Front.png",
    "Fury Green Painted Blue Side.png",
    "Fury Pink Painted brown Side.png",
    "Fury Purple Painted Front.png",
    "Fury Red Front.png",
    "Fury Red Side.png",
    "Fury Side Green.png",
    "Fury Turquoise Side.png",
    "Fury Wine Painted Orange Side.png",
    "Fury Yellow Side.png",
    "Happy BGreen Double Paint.png",
    "Happy Blue Paint.png",
    "Happy Double Pink Paint.png",
    "Happy Red Paint.png",
    "Happy.png",
    "Midst Blue Side.png",
    "Midst Brown Side.png",
    "Midst Green Paint Green Front.png",
    "Midst Green Side.png",
    "Midst Pink Paint Green Side.png",
    "Midst Red Paint Blue Side.png",
    "Midst Red Paint Brown Front.png",
    "Midst Red Paint Green Side.png",
    "Midst Red Paint Yellow Side.png",
    "Midst Red Side.png",
    "Midst Turquoise Side.png",
    "Midst Violet Paint Front.png",
    "Rounded Blue Front.png",
    "Rounded Gray Paint Front.png",
    "Rounded Pink Green Paint Front.png",
    "Rounded Red Blue Paint Front.png",
    "Rounded Red Front.png",
    "Rounded Sand Jade Paint Front.png",
    "Rounded Turquoise Blue Paint Front.png",
    "Rounded Turquoise Front.png",
    "Rounded Violet Paint  Front.png",
    "Shy Blue Purple Paint Side.png",
    "Shy Blue Red Paint Side.png",
    "Shy Brown Side.png",
    "Shy Dark Blue Paint Side.png",
    "Shy Gold Paint Side.png",
    "Shy Green Side.png",
    "Shy Light Blue Side.png",
    "Shy Pink Paint Side.png",
    "Shy Red Paint Side.png",
    "Shy Turquoise Red Paint Side.png",
    "Shy Yellow Side.png",
    "Suprised Blue Paint Yellow Side.png",
    "Suprised Purple Side.png",
    "Suprised Red Paint Blue Side.png",
    "Suprised Red Side.png",
    "Suprised Turquoise Side.png",
    "Triangle Blue Paint Red Front.png",
    "Triangle Blue Paint Turquoise Front.png",
    "Triangle Blue Paint Yellow Side.png",
    "Triangle Gold Paint Purple Front.png",
    "Triangle Purple Paint Green Side.png",
    "Triangle Red Paint Blue Side.png",
    "Triangle Red Paint Yellow Side.png",
    "serious yellow side.png"
  ],
  "Mouth": [
    "Angry Black.png",
    "Angry Green.png",
    "Angry Pink.png",
    "Angry Red.png",
    "Angry Turquoise.png",
    "Angry.png",
    "Cunning.png",
    "Happy Vampire Blue.png",
    "Happy Vampire Gray.png",
    "Happy Vampire Green.png",
    "Happy Vampire Naked.png",
    "Happy Vampire Pink.png",
    "Happy Vampire Red.png",
    "Happy Vampire Yellow.png",
    "Laughing Black.png",
    "Laughing Real Blue.png",
    "Laughing Real Green.png",
    "Laughing Real Pink.png",
    "Laughing.png",
    "Lined Mouth.png",
    "Neko Black.png",
    "Neko Green.png",
    "Neko Pink.png",
    "Neko.png",
    "Open Blue.png",
    "Open Real Pink.png",
    "Open Real Purple.png",
    "Open Red.png",
    "Open.png",
    "Ordinary Black.png",
    "Ordinary Blue.png",
    "Ordinary Mint.png",
    "Ordinary Red.png",
    "Ordinary.png",
    "Regular.png",
    "Rogue.png",
    "Serious Black.png",
    "Serious Red.png",
    "Serious.png",
    "Small Blue.png",
    "Small Red.png",
    "Small.png",
    "Smile Black.png",
    "Smile Blue.png",
    "Smile Red.png",
    "Smile.png",
    "Vampire Black.png",
    "Vampire Blue.png",
    "Vampire Naked.png",
    "Vampire Red.png"
  ],
  "Hair": [
    "Crest Black.png",
    "Crest Blonde.png",
    "Crest Blue.png",
    "Crest Brown.png",
    "Crest DoD Light.png",
    "Crest DoD.png",
    "Crest Green.png",
    "Crest Pink.png",
    "Crest Red.png",
    "Crest Silver.png",
    "Ponytail Black.png",
    "Ponytail Blonde.png",
    "Ponytail Blue.png",
    "Ponytail Brown.png",
    "Ponytail Pink.png",
    "Ponytail Red.png",
    "Ponytail Silver.png",
    "Samurai Black.png",
    "Samurai Blonde.png",
    "Samurai Blue.png",
    "Samurai Brown.png",
    "Samurai Green.png",
    "Samurai Pink.png",
    "Samurai Red.png",
    "Samurai Silver.png",
    "Short Black.png",
    "Short Blonde.png",
    "Short Brown.png",
    "Short Pink.png",
    "Short Red.png",
    "Short Silver.png"
  ],
  "Earring": [
    "Big Blue Feather.png",
    "Big Brown Feather.png",
    "Big Cobalt Feather.png",
    "Canine Blue.png",
    "Canine DoD.png",
    "Canine Ivory.png",
    "Canine Jade.png",
    "Canine Rubi.png",
    "Climber.png",
    "Double Ring.png",
    "Duck Fluorite.png",
    "Duck Gold.png",
    "Duck Rubi.png",
    "Gold Ring.png",
    "Gold and Turquoise Disc.png",
    "Jaguar.png",
    "None.png",
    "Single Old Gold Ring.png",
    "Single Ring.png",
    "Stones Jade.png",
    "Stones Obsidian.png",
    "Stones River.png",
    "Tip Jade.png",
    "Tip.png"
  ],
  "Mask": [
    "Mosaic Blue.png",
    "Mosaic Green.png",
    "Mosaic Red.png",
    "Mosaic Serpent Blue.png",
    "Mosaic Serpent Red.png",
    "None.png"
  ]
}
// module.exports = { femaleMaskedOG, femaleNoMaskedOG, maleMaskedOG, maleNoMaskedOG, MaleOpenMaskedOG }